README.md
go.mod
go.sum
pkg/plugins/file_decoder.go
pkg/plugins/file_gzip_decoder.go
pkg/plugins/files.go
pkg/plugins/files_base64_decoder.go
pkg/plugins/user.go
pkg/plugins/user_test.go
pkg/schema/loader_cloudinit.go
pkg/schema/loader_yip.go
pkg/schema/schema.go
pkg/schema/schema_test.go
pkg/utils/user.go

Add support for the cloudconfig file syntax, encoding it into the "boot"
yip stage.
Also adds support for more fine-grained control of the user setup and
file encoding when writing files to match cloudinit featureset
Signed-off-by: Ettore Di Giacinto <mudler@sabayon.org>

Add cloudinit support

---

go.mod
go.sum
pkg/executor/executor.go
pkg/plugins/datasource.go
pkg/plugins/dir.go
pkg/plugins/dir_test.go
pkg/plugins/files.go
pkg/plugins/files_test.go
pkg/schema/schema.go

This commit adds datasources from several providers (mostly cloud
providers). The datasource yip plugin is based on Linuxkit, however
the metadata utility from Linuxkit had to be forked and slightly
refactored to make it usable as a golang package.
Related to rancher-sandbox/cOS-toolkit#93

Add cloud datasources

---

pkg/plugins/datasource.go

Pre-create ConfigPath before extracting.

Ensure /run/config is created before extracting

---

README.md
pkg/plugins/datasource.go
pkg/schema/schema.go

This PR tries to load user-data from providers as YipConfig files,
if the parsing fails it does nor raise any error. User-data is stored to
the provided path. The file is named `userdata.yaml` if it could be
parsed as a YipConfig structure otherwise it is just called `userdata`.
In addition this commit also includes logic to apply the authorized keys
if the provider extracts a `ssh/authorized_keys` file.
Fixes rancher-sandbox/cOS-toolkit#93

Load user-data as YipConfig files

---

pkg/executor/executor.go
pkg/plugins/layout.go
pkg/plugins/layout_test.go
pkg/schema/schema.go
tests/console/console_mock.go

The Layout plugin mostly allows to expand the last partition to the disk
geometry and/or add additional partitions over the unpartitioned space.
In case there is no unpartitioned space on disk no changes are applied.
Fixes rancher-sandbox/cOS-toolkit#219

This commit adds a Layout plugin

---

pkg/plugins/user.go
pkg/plugins/user_test.go

This commit adds the SSH keys management within user creation.
Part of rancher-sandbox/cOS-toolkit#218

Include authorized ssh keys management in user plugin

---

pkg/plugins/environment.go
pkg/plugins/environment_test.go

This commit adds a check to verify parent directories for
environment files, if they do not exist they are created on the fly

Create any missing parent directory for env files

---

pkg/plugins/datasource.go
pkg/schema/loader_cloudinit.go
pkg/schema/schema_test.go

* Always save raw userdata content to disk on boot
* Allow userdata to use both cloud-init and yip syntax at the same time

Minor changes to userdata behavior

---

pkg/plugins/datasource.go

Omit datasource plugin execution if providers list is empty

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go
pkg/schema/schema.go

This commit adds explicit references to devices by path. This allows to
point devices that might not have yet any partition table on them.
Related to rancher-sandbox/cOS-toolkit#411

Add explicit references to devices by path

---

.github/workflows/release.yml
.github/workflows/test.yml
go.mod
go.sum
pkg/schema/schema.go
pkg/schema/schema_test.go
vendor/github.com/google/shlex/COPYING
vendor/github.com/google/shlex/README
vendor/github.com/google/shlex/go.mod
vendor/github.com/google/shlex/shlex.go
vendor/modules.txt

Currently if we try to load a dotNotation file and that file has spaces
in them, i.e. commands in quotes, it will panic and fail to load.
This patch changes the split of the file to use shlex which is context
aware of quotes and preserves that as one item insteaed of splitting it
further thus avoiding strange parsing like ">:true" which gojq fails to
parse completely.
Alos adds some tests for malformed files and half malformed files

Use shlex.Split to split dotNotation files

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go

xfs filesystems cannot have labels longer than 12 chars.
This patch adds a check at the start of the layout plugin before
touching the disk in order to check that the label is no longer than 12
characters if we are modifying an xfs partition.
Adds tests for it and the correct working of the check on non-xfs fs.
Also modifies the tests a bit so the mocking commands can be more
dynamic and sets vars for the deviceLabel and partition label so they
are all the same across all the tests.

layout: Check for valid label on xfs systems

---

pkg/schema/loader_cloudinit.go
pkg/schema/schema_test.go

This change fixes a bug in which permissons from write_files is
always set to 0.
By setting hostname in the boot stage services have initialized with the
old hostname.  Specifically I hit an issue where avahi would start before
the hostname was setup so mdns was not working properly

Fix write_files permissions and hostname

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go

Maybe the kernel doesnt have the partition table updated, so instead of
failing, we retry up to 5 times with a 1 second different between them
while calling the refresh on each iteration.
Also changes partprobe to blockdev as according to partprobe source, if
it cannot open a device it will exit with a 0 exit code, which can hide
real issues

Retry getting the partition on layout plugin

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go

Instead of directly doing the retry on the NewPart call, make it on each
fo the functions that are sensible to delay. Not only its better as they
are independent but its easier to see where it did fail AND if something
else is also calling those functions, they get the retry as well

Improve the partition reload detection

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go

Adds extra debugging output for the layout plugin and and also uses `udevadm settle` before several commands, blkid included as according to the man pages, its recommended to do in case there is pending events, so blkid/lsblk is not outdated

Extra debug for layout and use edevadm settle

---

README.md

There is an invalid comment in there that makes it as we can unset the size value and it will take all space available, but the size parameter is mandatory!

Fix layout readme

---

pkg/plugins/user.go
pkg/plugins/user_test.go

This commit reads "/etc/default/useradd" file to get default
home and shell for new users. In case the defaults file is not there
simply use "/home" and "/bin/sh" as defaults.
Fixes rancher-sandbox/os2#13

Set defaults for user's home and shell

---

go.mod
go.sum
vendor/github.com/davidcassany/linuxkit/pkg/metadata/providers/provider_cdrom.go
vendor/modules.txt

This commit update linuxkit dependency to ensure datasource plugin
closes all block devices after probing them.

Update linuxkit fork dependency

---

go.mod
go.sum
pkg/plugins/hostname.go
vendor/github.com/satori/go.uuid/README.md
vendor/github.com/satori/go.uuid/generator.go
vendor/modules.txt

Random data used to create UUIDs can contain zeros, resulting in predictable UUIDs and possible collisions.
Found in: github.com/satori/go.uuid@v1.2.0
Fixed in: github.com/satori/go.uuid@v1.2.1-0.20180404165556-75cca531ea76
More info: https://pkg.go.dev/vuln/GO-2022-0244

Fix GO-2022-0244

---

cmd/root.go
go.mod
go.sum
pkg/executor/default.go
pkg/executor/default_test.go
pkg/executor/executor.go
pkg/schema/schema.go
vendor/github.com/kendru/darwin/go/depgraph/depgraph.go
vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
vendor/github.com/onsi/ginkgo/v2/types/config.go
vendor/github.com/onsi/ginkgo/v2/types/version.go
vendor/github.com/spectrocloud-labs/herd/.golangci.yml
vendor/github.com/spectrocloud-labs/herd/Earthfile
vendor/github.com/spectrocloud-labs/herd/LICENSE
vendor/github.com/spectrocloud-labs/herd/README.md
vendor/github.com/spectrocloud-labs/herd/dag.go
vendor/github.com/spectrocloud-labs/herd/dag_options.go
vendor/github.com/spectrocloud-labs/herd/ops.go
vendor/github.com/spectrocloud-labs/herd/ops_options.go
vendor/modules.txt

This changes enhances the `yip` execution flow such as now allows introspection.
The PR changes the inner logic of the executor to just generate operations. The operations are loaded into a DAG which is executed.  
- A new flag `--analyze` is introduced, can be used as such to print the execution dag of a set of cloud config:
```
❯ ./yip -s network --analyze ~/_git/kairos/examples                                                                                                                                                                                                              
INFO[0000] 1.                                                                                            
INFO[0000]  <init> (background: false) (weak: false)     
INFO[0000] 2. …
```

Execute stages in a dag

---

go.mod
go.sum
pkg/plugins/datasource.go
pkg/plugins/datasource_test.go

Currently if you duplicate the datasources it would just keep adding
them to the list and running them one after the other wastinga lot of
time.
This patch just makes the datasources list unique before going over it.
Also makes metadata adquisition faster by running them in goroutines and then waiting for the
results to come back rather than running them in serial which can take a
long time for a large list of providers (providers * 2s timeout)
Also adds tests to the datasources.
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>

Only run unique datasources + parallel datasource adquisition + tests

---

.github/workflows/release.yml
.github/workflows/test.yml

- Run simple tests on push to master
- Run tests on PR
- use the go version from go.mod
Should fix the current issue when building once merged to master and allow releases to be build again

Fix release

---

.github/workflows/release.yml
pkg/plugins/layout.go
pkg/plugins/layout_test.go
tests/console/console_mock.go

We applied the same fix here:
https://github.com/kairos-io/kairos-agent/pull/32/files#diff-9bf4494bcc865684d4aeae7837925b1732855e863067c12a61f6f38e2fc16716
but we now want to use the yip implementation everywhere:
- kairos-agent (see link above)
- immucore: https://github.com/kairos-io/immucore/blob/0811f0f054b086708727a441988d3e93905838a1/internal/utils/layout_plugin.go#L18

Expand last partition after creating the partitions

---

pkg/executor/default.go
pkg/executor/default_test.go
pkg/schema/loader_cloudinit.go
tests/console/console_mock.go

Otherwise, in files which have no naming for example:
```
#cloud-config
stages:
default:
- commands:
- echo "01"
```
The name of the whole thing will be autogenerated with a fixed string
and it will collide if there is more than one op across different files.
Thus it would somehow miss the files in between the first and the last.
So if you had 5 files it would ignore the 2,3,4 in teh middle and only
run the first and last.
This is due the construction fo the op name which would be like:
`config.Name.Op_number`
Probably because this files are coming from the cloud init loader, the
config name will never change, thus generating ops with the final name
for all of them:
`Cloud init.0`
This patch removes the forced set of the config name to `Cloud init` so
it can be autogenerated based on the …

Remove forced names for cloud-init configs

---

pkg/plugins/systemd_firstboot.go
pkg/plugins/systemd_firstboot_test.go

Adding `--force` flag allows to make use of these systemd-firstboot plugin on distros that have default pre-configurations already present after a clean unconfigured installation. From `systemd-firstboot` help page:
```
--force     Overwrite existing files
```
I think it make sense allowing the plugin to overwrite any existing pre-configured file.

Add --force flag to systemd_firstboot plugin to overwrite existing files

---

pkg/plugins/layout.go

-i expects a hexadecimal value
-n should be used for the filesystem label
https://man7.org/linux/man-pages/man8/mkfs.vfat.8.html
Needed as part of https://github.com/kairos-io/kairos/issues/2281
so that this config:
```
add_partitions:
- fsLabel: COS_GRUB
size: 64
pLabel: efi
filesystem: "fat"
```
won't result in this error:
```
Volume ID must be a hexadecimal number
```

Set the vfat label using the correct flag

---

pkg/plugins/user.go
pkg/plugins/user_test.go

We dont want to fully skip the user update if it exists as it may be for a specific reason like updating groups and such, but if the entry does not have a specific user id set by the user object and the user already exists in the passwd file, we should reuse the userid as to not break existing files that may have permissions linked to that user
This should fix:
- users in config files appearing more than once, so their uid wont change
- ssh keys added to users than are updated after the key creation
- anything else adding a user to the passwd file and bumping the next uid free, as our calculation picks the latest free uid

Reuse existing user id if it exists

---

pkg/executor/default.go
pkg/executor/default_test.go

relates to https://github.com/kairos-io/kairos/issues/2488
description on the issue can be found on the ticket mentioned above

Handle duplicated names in a stage

---

go.mod
go.sum
pkg/plugins/user.go

https://systemd.io/UIDS-GIDS/#special-distribution-uid-ranges
Relevant: https://github.com/mauromorales/xpasswd/pull/3

Various fixes to allow uid to be in a correct range

---

go.mod
go.sum
pkg/plugins/dns.go

Package moby is updated and now the resolvconf part points to internal packages which makes it un-importable to use directly
As we only want to write a simple resolv.conf so we can just add a few lines of code to do so
This also solves https://osv.dev/vulnerability/GO-2024-3005 by bumping github.com/moby/moby

Drop resolvconf import

---

pkg/plugins/layout.go
pkg/plugins/layout_test.go

Goal of this PR is to be able to handle simple single disk btrfs formated partitions.
This way the persistent partition can be used by tools like https://github.com/lxc/incus for containers and VM disks

Add btrfs partition support

---

cmd/root.go
pkg/executor/default.go
pkg/plugins/commands.go
pkg/plugins/common.go
pkg/plugins/layout.go

see commits for explanation
Signed-off-by: Itxaka <itxaka@kairos.io>

several small improvements

---

pkg/plugins/timesyncd.go
pkg/plugins/timesyncd_test.go

- Set empty value if the value as strings if value is empty instead of omitting the value
- Write config to /etc/systemd/timesyncd.conf.d/10-yip.conf to properly override the existing config and any others shipped with the system

Improve timesyncd plugin

---

pkg/console/console.go
pkg/executor/default.go

With a config like this:
```
#cloud-config
stages:
initramfs:
- name: "test"
commands:
- sleep 15
- echo "hello"
```
This is the output:
```
$ LOGLEVEL=debug go run main.go -s initramfs .
INFO[0000] yip version -g                               
INFO[0000] Running stage: initramfs                     
DEBU[0000] Generating op for stage 'test.yaml.0'        
DEBU[0000] Generating op for stage 'test.yaml.test'     
DEBU[0000] Reading 'test.yaml'                          
DEBU[0000] Executing stage 'test.yaml.0'                
INFO[0000] Processing stage step 'test.yaml.0'. ( commands: 0, files: 0, ... ) 
DEBU[0000] Stage: schema.Stage{}                        
DEBU[0000] Device field empty, skipping layout plugin   
DEBU[0000] Reading 'test.yaml'                          
DEBU[0000] …
```

Print a message if a stage is taking more than 10 seconds

---

pkg/plugins/packages.go

```
218aff01fc75:/ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP6"
VERSION_ID="15.6"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp6"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

Use SUSE installer for SLE family

---

pkg/executor/default_test.go
pkg/plugins/commands_test.go
pkg/plugins/datasource_test.go
pkg/plugins/dir_test.go
pkg/plugins/dns_test.go
pkg/plugins/download_test.go
pkg/plugins/environment_test.go
pkg/plugins/files_test.go
pkg/plugins/git_test.go
pkg/plugins/if_test.go
pkg/plugins/packages_test.go
pkg/plugins/ssh_test.go
pkg/plugins/sysctl_test.go
pkg/plugins/systemctl_test.go
pkg/plugins/systemd_firstboot_test.go
pkg/plugins/timesyncd_test.go
pkg/plugins/unpack_image_test.go
pkg/plugins/user_test.go
tests/console/console.go

Make sure the test console is using its own copy, we access via pointer, and the reset cleans our own commands copy, instead of the shared one

Values and pointers and copies, oh my

---

pkg/schema/loader_cloudinit.go
pkg/schema/schema_test.go

Check if SSH keys are from GitLab or GitHub and move them to the network stage if necessary. This ensures that keys needing network access are handled appropriately during the configuration process.
Fixes https://github.com/kairos-io/kairos/issues/3626

feat: Move SSH keys to network stage if required
